### ISSUE TITLE
Wifi Disconnect Loop

### ISSUE THREAD

**Issue by aaronweaver** [Gixy31/ESP32-PoolMaster#16]
If for some reason the wifi cannot reconnect the while statement check continues in an endless loop.

[ 1289 ] [WiFi] Connecting to WiFi...
..E (6107) wifi:Set status to INIT
[ 2951 ] [WiFi] Connection lost
...[ 4479 ] [WiFi] Connection lost
....[ 6479 ] [WiFi] Spurious disconnect event ignored
..........................................................................................................................................................................................................................................

```
WiFi.reconnect();
    while(WiFi.status() != WL_CONNECTED) {
      delay(500);
      Serial.print(":");
    }
```

**Comment by Gixy31** [comment]
I know. As Microsoft says: it's not a bug, it's a feature... I never had a total failure of the WiFi, but if you need it, you can easily implement a retry count.
It has been confirmed that the STA_DISCONNECTED event occuring just before STA_GOT_IP is now normal on the new ESP32_ARDUINO release, justifying the workaround.
