### ISSUE TITLE
Formules calcul pH orp psi

### ISSUE THREAD

**Issue by cloubier** [Gixy31/ESP32-PoolMaster#17]
Bonjour
Peux tu partager du détails sur les formules de calcul ?

**Comment by Gixy31** [comment]
Ben, rien de sorcier. Avec le setup de l'ADS1115, on a 6,144 V pour 32767 en valeur binaire sur 15 bits, donc  en multipliant la valeur binaire par 0.1875/1000 on obtient les volts (0,1875/1000 c'est pareil que 6.144/32768) . Ensuite on fait l'étalonnage des sondes dans les solutions étalons et on transforme les Volts en pH ou mv d'Orp. Pour la pression, j'ai un manomètre sur le circuit d'eau qui me permet d'étalonner la mesure.
On pourrait éviter le passage par les volts et passer directement de la valeur binaire à la valeur physique, mais quand on fait la mise au point du circuit, cela permet de valider la mesure avec un voltmètre à l'entrée du convertisseur ADS1115.
