### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ippodrome** [Gixy31/ESP32-PoolMaster#19]
Hi! 
Is there any documentation on how to install this software and set it up?
Im new to platformIO but have managed to install it and connect to the ESP32 but then I'm quite lost.
Where do I setup my wifi settings and how do i connect to the board when installed?

Thanks!

**Comment by Gixy31** [comment]
Look at config.h and platormio.ini. Learn more about platformio and experiment by yourself. I cannot do this for you.

**Comment by ippodrome** [comment]
Thank you for replying. Will try to learn! :P
