### ISSUE TITLE
Board

### ISSUE THREAD

**Issue by vaughnlfisher** [Gixy31/ESP32-PoolMaster#2]
Where can i get my hands on the board

**Comment by Gixy31** [comment]
Well, first by being polite, saying at least hello, please or something like that, which seems to be ignored by new generations... And second there is a pdf file called PoolMaster.pdf at the root of the directory with a 3D view and the schematic.

**Comment by vaughnlfisher** [comment]
> 
> 
> Well, first by being polite, saying at least hello, please or something like that, which seems to be ignored by new generations... And second there is a pdf file called PoolMaster.pdf at the root of the directory with a 3D view and the schematic.

My question was rude so i appoloise.

I am not of the new generation even though i wish i was sometimes.

The pdf is a good representation. where could I get the board made? Have you had it made?

Thanks,

**Comment by Gixy31** [comment]
I usualy have my boards made by JLCPCB, and yes this one is made and operational.

**Comment by vaughnlfisher** [comment]
Hi
Do you have a Gerber file for me please? JLPCB is asking for one?
Thanks again!

**Comment by Gixy31** [comment]
zip file added. Enjoy.

**Comment by vaughnlfisher** [comment]
Thanks 🙏 

Regards
Vaughn
Fisher

**Comment by drivers1** [comment]
I'm interested too... Thanks very much!!!
One question. Are you order in JLPCB with option SMT Assembly??
Regards

**Comment by Gixy31** [comment]
@drivers1 
No, I do it by myself. SMD are big enough to be soldered by hand, with a binocular to help.
