### ISSUE TITLE
No probe readings

### ISSUE THREAD

**Issue by REDDE4D** [Gixy31/ESP32-PoolMaster#20]
Hello i am currently in the process of recreating this awesome Project for my Pool.

Everything but the probes functions. I get readings of pH 40.4 and ORP of -897mV  
I tried running an I2C scanner but it only finds the address 0x38 wich should be the PCF8574A.  
The ADS1115 wich should have an address of 0x48 is not found.   
I checked all physical connections and checked the voltages of the components even used a new mcu but still no luck.

Does someone have or had a simular problem?

**Comment by Gixy31** [comment]
Hi,
What do you mean by "recreating"? Do you use my board or one of your own? 

Did you see that there is now two options for probes connection: INT_ADS1115 which uses the ADS1115 of the mother-board, and EXT_ADS1115 which uses a dedicated pH_Orp board with its own ADS1115, whose address should not be the same than the other one which is only used for water pressure in this case. The configuration is defined in config.h and I'm afraid that at the moment it is defined as EXT_ADS1115, so the software is looking for address 0x49.

0x48 is the address of the ADS1115 if you wired it with the address pin to GND. Did you checked the ADS1115 itself: if it is not found, may be it is the culprit.

Are those readings obtained with the probes into the water? Are you sure of the probes wiring?

How are the probes connected: Phydget boards or something else? Try to disconnect the probes (AN0, AN1), inject some known analog voltage between 0 and 5V and activate DBG_DEBUG mode to see traces and validate the measurement chain.

Well, lot of questions, but difficult to help without knowing anything of your configuration.

**Comment by REDDE4D** [comment]
Sorry recreating may be a wrong term. Im use your board design.  
In the config the connection option is set to INT\_ADS1115.  
The probes are connected via the Phydget adapter and the dfrobot gravity isolators and sitting in an calibration fluid while meassuring.  
Applying an voltag of 4V to A0 and A1 didn't result in a change. It seems like the ADS1115 might be the problem as it infact didn't get picked up by the i2c scanner. I ordered some replacements that get deliverd tomorrow so i need to check back then.

I'll let you know if i have any updates. Thanks for your help so far and keep up the awesome work :)

Cheers

**Comment by REDDE4D** [comment]
Hey,

just a quick update. It infact was a dead ADS1115. Replaced it and now everything works like a charm.  
Thanks again for you help and have a nice weekend.

Cheers

**Comment by Gixy31** [comment]
:-)

**Comment by REDDE4D** [comment]
One simple question I have left is about the calibration of the pH probe. Does the calibrated values survive a reboot or possible reflash?
Or do I have to recalibrate each time?

**Comment by Gixy31** [comment]
When you calibrate the probes , the coefficients are updated in EEPROM and so they "survive" reboot and/or reflash. They're only replaced if you change CONFIG_VERSION in config.h, where they take the values defined in setup.cpp
