### ISSUE TITLE
Calibration of Pressure Sensor

### ISSUE THREAD

**Issue by REDDE4D** [Gixy31/ESP32-PoolMaster#21]
Hey,
does anyone know a good way to calibrate the pressure sensor?
I'm using this Sensor: https://amzn.eu/d/ekGDIym

It shows -0.9 on the display and doesn't change when the pump is running. 
The manual gauge shows around 0.5bar when the pump is running.

Looking at the mqtt values they report as follows
Pump Off: -9.3122074991 PSI 
Pump On after 15 min: -8.752225019 PSI

Thanks in advance

**Comment by Gixy31** [comment]
You shouldn't have negative values. 0.5 bar when the pump is running is very low, usually it is between 0.8 and 1.5 bar. MQTT values should be the same than displayed. So activate traces and debug...
This type of sensor are quite linear with 0,5V - 4,5V measuring 0 to 100psi, you can start with those values to set the calibration coefficients.
