### ISSUE TITLE
LED State

### ISSUE THREAD

**Issue by csc-solution** [Gixy31/ESP32-PoolMaster#22]
Hi,

is there a little description, which led is for what state? I couldn't find it in the readme files.

Thanks in advance

Kind regards,
Tom

**Comment by Gixy31** [comment]
Hi,I dont remember if there is something like that but you can have a look to the code loops.cpp Le 5 juin 2024 03:32, csc-solution ***@***.***> a écrit :
Hi,
is there a little description, which led is for what state? I couldn't find it in the readme files.
Thanks in advance
Kind regards,
Tom

**Comment by csc-solution** [comment]
Thanks a lot.
