### ISSUE TITLE
Pick Place for main board

### ISSUE THREAD

**Issue by vaughnlfisher** [Gixy31/ESP32-PoolMaster#24]
Hi

It's me again :)

Could i get the pick place file for the main board please?

Thanks!

**Comment by Gixy31** [comment]
Hi,
There is not P&P file as there are modules on the board (Power supply, ADS1115, level shifter, ESP32_DevKit) that are surely not available in the component store of the manufacturer. I think you have better to populate the board by yourself, it's not difficult, with only a few SMD LEDs and resistors , everything else is thru hole.
Regards
