### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by vaughnlfisher** [Gixy31/ESP32-PoolMaster#3]
Sorry to bother again!
Total newbee here!
Got the PCB's they worked a treat.
Struggling to find the correct resistor components to fit, hence the request for BOM?
Would also like to know what level sensors you used for the chlorine and acid solutions?

Thanks again!
V

**Comment by Gixy31** [comment]
BoM file added.

**Comment by kifeo** [comment]
Hello,

Thanks for your work on this !
While getting the items from the BOM, I've found out that most of the links are not directing me to the correct items.

Would it be possible to update the BOM ?

Thanks !
