### ISSUE TITLE
librairie ads1115

### ISSUE THREAD

**Issue by tiji2486** [Gixy31/ESP32-PoolMaster#4]
A priori pas la bonne version de ads1115, elle ne veut pas s'installer : 

Library Manager: Installing ADS1115 @ 1.0.0
Warning! Could not find the package with 'ADS1115 @ 1.0.0' requirements for your system 'windows_amd64'

j'ai celle ci :  https://github.com/jrowberg/i2cdevlib.git

**Comment by Gixy31** [comment]
Non, il faut aller la chercher directement ici : https://lygte-info.dk/project/ADS1115Library%20UK.html
lien de téléchargement : https://lygte-info.dk/pic/Projects/ADS1115Library/ADS1115.zip
Je l'ai trouvée par hasard, mais elle est bien faite, et permet en particulier de fonctionner en asynchrone (on n'attend pas les conversions).

**Comment by tiji2486** [comment]
ok merci, plus d'erreurs sur cette librairies
