### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by vaughnlfisher** [Gixy31/ESP32-PoolMaster#5]
Sorry to ask for help again

I import the json grafan file but no panels show up in the newly created dashboard.
Do you think I’ve done something wrong?
Any ideas?

Thanks

**Comment by Gixy31** [comment]
Of course you have created an InfluxDB database, populated by the NodeRed flow also included...
I imagine that you understand the global functionning of the system:
- PoolMaster (ESP32) sends messages on MQTT topics to a MQTT broker;
- the broker transfer those messages to subscribers of the given topics, in this case the NodeRed flow;
- the flow processes the data and send measurement to the InfluxDB database;
- Grafana then periodically retrieves data from InfluxDB and display them on a dashboard.
That means that you have to set up MQTT broker, Nodered server and flow, InfluxDB database and grafana. Did you do all this?
