### ISSUE TITLE
Tank volume "problem"

### ISSUE THREAD

**Issue by vaughnlfisher** [Gixy31/ESP32-PoolMaster#6]
Hi

Very good project my system is up and running, plus or minus. I have an issue potentially where the tank fill volume drops to zero in one movement. I dont understand why?

See attached picture of Grafan. Top panel show where over time ive set the tanks to 100% and randomly they drop to zero %

Any ideas?
![tank volume](https://user-images.githubusercontent.com/45875201/124556024-ab145e00-de2f-11eb-95b7-d6d5c94b1db1.jpg)

**Comment by Gixy31** [comment]
Hi,
Looking at pumps activities or ORP value, your system looks a bit strange. If you've modified the sofware, I can't help without seeing the code. I don't have this problem at all. The last version of my sofware has some modifications in the pump library and in the code to manage tank levels. May be you can try this new version.

**Comment by vaughnlfisher** [comment]
Hi

I’ve not changed anything. Which specific files are you referring to? I have updated the settings etc but not code.

Thanks again

**Comment by Gixy31** [comment]
Your pumps graph should look like this one. Did you set values in liters/min for the pH and chlorine pumps?
I encourage you to take the last version of the code and review your settings.
![image](https://user-images.githubusercontent.com/73664395/124583648-95b12b00-de53-11eb-8fd0-f5200169d55c.png)

**Comment by vaughnlfisher** [comment]
Thanks a million
I would expect the same graph as you. My graph suggests nothing is chinging in terms of the chlorine or ph pumps i.e. they stay off. If they stay off surely the tank should stay at 100%? I would expect a constant 100% on the tanks. Im testing outside of the pool environemt to make sure everything is good before i connect to the pool pipework.

**Comment by vaughnlfisher** [comment]
Hi
I now have a pressure error at a 0.64 which I think is preventing any automatic dosing. My pump is not connected to the system, it’s independent. I have not modified any code.
![3B701869-4374-42E1-B0A0-B8E18D5FD4FE](https://user-images.githubusercontent.com/45875201/128203283-521e83b8-2dbe-4f43-9f67-92ddf0a559c6.jpeg)

**Comment by Gixy31** [comment]
This is as per design:
By default, the water pressure threshold is set at 0.7 bar. You can change it either on the Nodered Settings dashboard or in the setup.cpp file where the storage structure is initialized.
If the pressure is still lower than this threshold 45 sec after filtration start, you have an alarm and everything stop.

**Comment by vaughnlfisher** [comment]
thanks for your help
![Uploading D8EDD94E-EA69-4F35-876F-723C484EFB61.jpeg…]()


Hi changed it in the code, there is no where to set the medium threshold in node red. Still same problem?

**Comment by Gixy31** [comment]
Normally there is one, called WPr Low in the settings dashboard (which is a more appropriate name).

**Comment by vaughnlfisher** [comment]
Definitely nothing like that.
![Uploading F0DD7F4A-DA2E-49CB-A510-254E7D9FC501.jpeg…]()

**Comment by vaughnlfisher** [comment]
Hi

I don’t see anything like that?
Maybe I’ve done something wrong?

![AA14787D-168B-4C84-AE4F-5D91348D007A](https://user-images.githubusercontent.com/45875201/128238925-9d99830c-0b70-4f72-8eab-9d3d52c7253d.jpeg)

Sorry for being a bother

**Comment by Gixy31** [comment]
Yes, this is the original Nodered dashboard. I modified it a lot since that. It is not so hard to add more fields such as Water Pressure  medthreshold, and you can then learn a lot on how Nodered works :-)
