### ISSUE TITLE
Buy HARDWARE for esp32-poolmaster

### ISSUE THREAD

**Issue by zhivko** [Gixy31/ESP32-PoolMaster#7]
Hi is it possible to buy hardware somewhere or at least buy pcbs somewhere?
Have you built board and it has been put in work somewhere or is this hypothetical?

**Comment by Gixy31** [comment]
Hi,
The gerber files used to build the PCB are in the zip file in the Code section. This is a real project running for 18 months now. More discussion and pictures here : https://forum.arduino.cc/t/poolmaster-gestion-et-domotisation-de-ma-piscine/563058/624 (sorry, in french).
