### ISSUE TITLE
Gerber files

### ISSUE THREAD

**Issue by ippodrome** [Gixy31/ESP32-PoolMaster#8]
Hi!
Thank you for this fork! 

I’m having some issues with the pcb when it’s was sent to the pcb-maker.

they sent me this:

![7D0ED0A3-CBDB-43F4-A84F-B6F3CCC8788C](https://user-images.githubusercontent.com/68822416/181209950-3a79662b-72ba-471b-bc37-bee5517b856e.jpeg)

i have no idea what this means or how to fix it. What should I do? 

Thank you! / viktor

**Comment by Gixy31** [comment]
Hi,
Both are valid: the circles on the GKO layer ( Keep-out layer) are used to avoid traces routing too close from the holes. This is used only during PCB design. You can answer to your manufacturer to keep only drill holes and discard GKO layer.

**Comment by ippodrome** [comment]
Thank you very much for the quick reply! 👏🏼
Will tell them! 
😊
